-- Esquema base reproducible. Debe ejecutarse antes de las migraciones P0.
-- Usa IF NOT EXISTS para poder incorporarlo a proyectos ya creados.

create table if not exists public.productos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  categoria text not null,
  precio numeric(12,2) not null,
  precio_original numeric(12,2),
  imagen text not null,
  stock integer not null default 0,
  descripcion text,
  caracteristicas jsonb,
  imagenes_extra jsonb,
  video_url text,
  marca text,
  garantia text
);

create table if not exists public.perfiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  username text,
  direccion_principal jsonb,
  direcciones_guardadas jsonb not null default '[]'::jsonb
);

create table if not exists public.pedidos (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references auth.users(id) on delete restrict,
  items jsonb not null default '[]'::jsonb,
  total numeric(12,2) not null default 0,
  metodo_pago text not null,
  estado text not null default 'pedido_recibido',
  codigo_seguimiento text not null,
  cliente_nombre text,
  cliente_email text,
  costo_delivery numeric(12,2) not null default 0,
  costo_real_delivery numeric(12,2),
  distancia_delivery double precision,
  direccion_cliente text,
  notas_delivery text,
  tiene_regalo boolean not null default false,
  fecha timestamptz not null default now(),
  fecha_pago_verificado timestamptz,
  fecha_preparacion timestamptz,
  fecha_envio timestamptz,
  fecha_entrega timestamptz
);

create table if not exists public.resenas (
  id bigint generated by default as identity primary key,
  producto_id bigint not null references public.productos(id) on delete cascade,
  usuario_id uuid not null references auth.users(id) on delete cascade,
  usuario_nombre text not null,
  calificacion integer not null check (calificacion between 1 and 5),
  comentario text,
  aprobada boolean not null default false,
  fecha timestamptz not null default now()
);

create index if not exists resenas_producto_fecha_idx on public.resenas(producto_id, fecha desc);
create index if not exists pedidos_usuario_fecha_idx on public.pedidos(usuario_id, fecha desc);
