-- MosaMeli: fiabilidad del checkout y de la operacion de pedidos.
-- Aplica esta migracion despues de 202609260003_pago_declarado.sql.

begin;

alter table public.pedidos
  add column if not exists reserva_expira_en timestamptz,
  add column if not exists stock_liberado_en timestamptz;

update public.pedidos
   set reserva_expira_en = fecha + interval '30 minutes'
 where reserva_expira_en is null
   and estado = 'pedido_recibido'
   and pago_declarado is null;

create table if not exists public.pedido_historial (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null references public.pedidos(id) on delete cascade,
  estado_anterior text,
  estado_nuevo text not null,
  cambiado_por uuid,
  fecha timestamptz not null default now()
);

create index if not exists pedido_historial_pedido_fecha_idx
  on public.pedido_historial (pedido_id, fecha desc);

alter table public.pedido_historial enable row level security;
revoke all on table public.pedido_historial from anon, authenticated;
grant select on table public.pedido_historial to authenticated;

drop policy if exists pedido_historial_select_own_or_admin on public.pedido_historial;
create policy pedido_historial_select_own_or_admin
  on public.pedido_historial for select
  to authenticated
  using (
    public.is_admin() or exists (
      select 1 from public.pedidos p
       where p.id = pedido_id and p.usuario_id = auth.uid()
    )
  );

create table if not exists public.notificaciones_pendientes (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null references public.pedidos(id) on delete cascade,
  tipo text not null check (tipo in ('confirmacion', 'estado')),
  intentos integer not null default 0 check (intentos >= 0),
  siguiente_intento timestamptz not null default now(),
  ultimo_error text,
  completada_en timestamptz,
  creada_en timestamptz not null default now(),
  unique (pedido_id, tipo, completada_en)
);

create index if not exists notificaciones_pendientes_reintento_idx
  on public.notificaciones_pendientes (siguiente_intento)
  where completada_en is null;

alter table public.notificaciones_pendientes enable row level security;
revoke all on table public.notificaciones_pendientes from anon, authenticated;

create or replace function public.cotizar_delivery(
  p_lat double precision,
  p_lng double precision,
  p_momento timestamptz default now()
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_distancia double precision;
  v_base numeric;
  v_nocturno numeric := 0;
  v_domingo numeric := 0;
  v_hora integer;
  v_dia integer;
  origin_lat constant double precision := -11.9726;
  origin_lng constant double precision := -76.7790;
begin
  if p_lat is null or p_lng is null or p_lat < -90 or p_lat > 90 or p_lng < -180 or p_lng > 180 then
    raise exception 'UBICACION_INVALIDA';
  end if;

  v_distancia := 6371 * 2 * asin(sqrt(
    power(sin(radians(p_lat - origin_lat) / 2), 2) +
    cos(radians(origin_lat)) * cos(radians(p_lat)) *
    power(sin(radians(p_lng - origin_lng) / 2), 2)
  ));

  if v_distancia > 10 then
    raise exception 'FUERA_DE_COBERTURA';
  end if;

  v_base := case
    when v_distancia <= 2 then 5
    when v_distancia <= 4 then 7
    when v_distancia <= 7 then 10
    else 15
  end;

  v_hora := extract(hour from p_momento at time zone 'America/Lima');
  v_dia := extract(dow from p_momento at time zone 'America/Lima');
  if v_hora >= 20 or v_hora < 7 then v_nocturno := 3; end if;
  if v_dia = 0 then v_domingo := 2; end if;

  return jsonb_build_object(
    'distancia', round(v_distancia::numeric, 2),
    'base', v_base,
    'recargo_nocturno', v_nocturno,
    'recargo_domingo', v_domingo,
    'costo', v_base + v_nocturno + v_domingo
  );
end;
$$;

revoke all on function public.cotizar_delivery(double precision, double precision, timestamptz) from public;
grant execute on function public.cotizar_delivery(double precision, double precision, timestamptz) to anon, authenticated;

create or replace function public.liberar_stock_pedido(p_pedido_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.pedidos%rowtype;
  v_item record;
begin
  select * into v_order from public.pedidos where id = p_pedido_id for update;
  if not found or v_order.stock_liberado_en is not null then return; end if;

  for v_item in
    select (item ->> 'id')::bigint as id,
           sum((item ->> 'cantidad')::integer)::integer as cantidad
      from jsonb_array_elements(v_order.items) item
     group by (item ->> 'id')::bigint
  loop
    update public.productos set stock = stock + v_item.cantidad where id = v_item.id;
  end loop;

  update public.pedidos set stock_liberado_en = now() where id = p_pedido_id;
end;
$$;

revoke all on function public.liberar_stock_pedido(bigint) from public, anon, authenticated;

create or replace function public.expirar_reservas()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order record;
  v_count integer := 0;
begin
  for v_order in
    select id, estado from public.pedidos
     where estado = 'pedido_recibido'
       and pago_declarado is null
       and stock_liberado_en is null
       and reserva_expira_en <= now()
     for update skip locked
  loop
    perform public.liberar_stock_pedido(v_order.id);
    update public.pedidos set estado = 'cancelado' where id = v_order.id;
    insert into public.pedido_historial (pedido_id, estado_anterior, estado_nuevo)
    values (v_order.id, v_order.estado, 'cancelado');
    v_count := v_count + 1;
  end loop;
  return v_count;
end;
$$;

revoke all on function public.expirar_reservas() from public, anon;
grant execute on function public.expirar_reservas() to authenticated;

create or replace function public.registrar_notificacion_pendiente(
  p_pedido_id bigint,
  p_tipo text,
  p_error text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_tipo not in ('confirmacion', 'estado') then raise exception 'TIPO_INVALIDO'; end if;
  if not exists (
    select 1 from public.pedidos
     where id = p_pedido_id
       and (usuario_id = auth.uid() or public.is_admin())
  ) then raise exception 'PEDIDO_NO_ENCONTRADO'; end if;

  insert into public.notificaciones_pendientes (pedido_id, tipo, ultimo_error)
  values (p_pedido_id, p_tipo, left(coalesce(p_error, ''), 500));
end;
$$;

revoke all on function public.registrar_notificacion_pendiente(bigint, text, text) from public, anon;
grant execute on function public.registrar_notificacion_pendiente(bigint, text, text) to authenticated;

create or replace function public.crear_pedido(
  p_items jsonb,
  p_metodo_pago text,
  p_direccion text,
  p_lat double precision,
  p_lng double precision,
  p_notas text default '',
  p_idempotency_key uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_user_id uuid := auth.uid();
  v_email text := auth.jwt() ->> 'email';
  v_username text;
  v_existing public.pedidos%rowtype;
  v_order_id bigint;
  v_code text;
  v_token text;
  v_subtotal numeric := 0;
  v_quote jsonb;
  v_delivery numeric;
  v_distance double precision;
  v_items jsonb := '[]'::jsonb;
  v_item record;
  v_product record;
  v_now timestamptz := now();
begin
  if v_user_id is null then raise exception 'AUTH_REQUIRED'; end if;
  if v_email is null or length(trim(v_email)) = 0 then raise exception 'EMAIL_REQUERIDO'; end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' then raise exception 'ITEMS_INVALIDOS'; end if;
  if jsonb_array_length(p_items) < 1 or jsonb_array_length(p_items) > 50 then raise exception 'CANTIDAD_PRODUCTOS_INVALIDA'; end if;
  if p_metodo_pago is null or p_metodo_pago not in ('plin', 'yape', 'transferencia') then raise exception 'METODO_PAGO_INVALIDO'; end if;
  if p_direccion is null or length(trim(p_direccion)) < 5 or length(p_direccion) > 300 then raise exception 'DIRECCION_INVALIDA'; end if;
  if length(coalesce(p_notas, '')) > 500 then raise exception 'NOTAS_INVALIDAS'; end if;
  if p_idempotency_key is null then raise exception 'IDEMPOTENCY_KEY_REQUERIDA'; end if;

  perform public.expirar_reservas();

  select * into v_existing from public.pedidos
   where usuario_id = v_user_id and idempotency_key = p_idempotency_key;
  if found then
    if v_existing.estado = 'cancelado' and v_existing.stock_liberado_en is not null then
      update public.pedidos set idempotency_key = null where id = v_existing.id;
    else
      return jsonb_build_object(
        'id', v_existing.id,
        'total', v_existing.total,
        'costo_delivery', v_existing.costo_delivery,
        'distancia_delivery', v_existing.distancia_delivery,
        'reserva_expira_en', v_existing.reserva_expira_en,
        'reutilizado', true
      );
    end if;
  end if;

  v_quote := public.cotizar_delivery(p_lat, p_lng, v_now);
  v_delivery := (v_quote ->> 'costo')::numeric;
  v_distance := (v_quote ->> 'distancia')::double precision;

  for v_item in
    select id, sum(cantidad)::integer as cantidad
      from jsonb_to_recordset(p_items) as item(id bigint, cantidad integer)
     group by id order by id
  loop
    if v_item.cantidad is null or v_item.cantidad <= 0 or v_item.cantidad > 99 then raise exception 'CANTIDAD_INVALIDA'; end if;
    select id, nombre, precio, stock into v_product
      from public.productos where id = v_item.id for update;
    if not found then raise exception 'PRODUCTO_NO_DISPONIBLE'; end if;
    if v_product.stock < v_item.cantidad then raise exception 'STOCK_INSUFICIENTE'; end if;

    v_subtotal := v_subtotal + (v_product.precio * v_item.cantidad);
    v_items := v_items || jsonb_build_array(jsonb_build_object(
      'id', v_product.id, 'nombre', v_product.nombre,
      'precio', v_product.precio, 'cantidad', v_item.cantidad
    ));
    update public.productos set stock = stock - v_item.cantidad where id = v_product.id;
  end loop;

  if v_items = '[]'::jsonb then raise exception 'CARRITO_VACIO'; end if;
  select username into v_username from public.perfiles where id = v_user_id;
  v_username := coalesce(nullif(v_username, ''), split_part(v_email, '@', 1));
  v_token := encode(gen_random_bytes(24), 'hex');
  v_code := 'MOSA-' || to_char(v_now at time zone 'America/Lima', 'YYYYMMDD') || '-' ||
            upper(substr(encode(gen_random_bytes(4), 'hex'), 1, 6));

  insert into public.pedidos (
    usuario_id, items, total, metodo_pago, estado, codigo_seguimiento,
    tracking_token, idempotency_key, cliente_nombre, cliente_email,
    costo_delivery, distancia_delivery, direccion_cliente, notas_delivery,
    tiene_regalo, fecha, reserva_expira_en
  ) values (
    v_user_id, v_items, round(v_subtotal + v_delivery, 2), p_metodo_pago,
    'pedido_recibido', v_code, v_token, p_idempotency_key, v_username, v_email,
    v_delivery, v_distance, left(trim(p_direccion), 300),
    nullif(left(trim(coalesce(p_notas, '')), 500), ''), v_subtotal >= 150,
    v_now, v_now + interval '30 minutes'
  ) returning id into v_order_id;

  insert into public.pedido_historial (pedido_id, estado_anterior, estado_nuevo, cambiado_por)
  values (v_order_id, null, 'pedido_recibido', v_user_id);

  return jsonb_build_object(
    'id', v_order_id,
    'total', round(v_subtotal + v_delivery, 2),
    'costo_delivery', v_delivery,
    'distancia_delivery', v_distance,
    'reserva_expira_en', v_now + interval '30 minutes',
    'reutilizado', false
  );
end;
$$;

revoke all on function public.crear_pedido(jsonb, text, text, double precision, double precision, text, uuid) from public, anon;
grant execute on function public.crear_pedido(jsonb, text, text, double precision, double precision, text, uuid) to authenticated;

create or replace function public.declarar_pago(p_pedido_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_order public.pedidos%rowtype;
begin
  if v_user_id is null then raise exception 'AUTH_REQUIRED'; end if;
  perform public.expirar_reservas();
  select * into v_order from public.pedidos
   where id = p_pedido_id and usuario_id = v_user_id for update;
  if not found then raise exception 'PEDIDO_NO_ENCONTRADO'; end if;
  if v_order.estado = 'cancelado' then raise exception 'PEDIDO_EXPIRADO'; end if;
  if v_order.estado <> 'pedido_recibido' then raise exception 'PEDIDO_YA_VERIFICADO'; end if;
  if v_order.pago_declarado is not null then
    return jsonb_build_object(
      'id', v_order.id, 'codigo_seguimiento', v_order.codigo_seguimiento,
      'tracking_token', v_order.tracking_token, 'total', v_order.total,
      'metodo_pago', v_order.metodo_pago, 'pago_declarado', v_order.pago_declarado
    );
  end if;

  update public.pedidos set pago_declarado = now(), reserva_expira_en = null
   where id = p_pedido_id;
  return jsonb_build_object(
    'id', v_order.id, 'codigo_seguimiento', v_order.codigo_seguimiento,
    'tracking_token', v_order.tracking_token, 'total', v_order.total,
    'metodo_pago', v_order.metodo_pago, 'pago_declarado', now()
  );
end;
$$;

revoke all on function public.declarar_pago(bigint) from public, anon;
grant execute on function public.declarar_pago(bigint) to authenticated;

create or replace function public.cambiar_estado_pedido(p_pedido_id bigint, p_estado text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.pedidos%rowtype;
  v_allowed boolean := false;
begin
  if not public.is_admin() then raise exception 'FORBIDDEN'; end if;
  select * into v_order from public.pedidos where id = p_pedido_id for update;
  if not found then raise exception 'PEDIDO_NO_ENCONTRADO'; end if;
  if p_estado = v_order.estado then return jsonb_build_object('id', v_order.id, 'estado', v_order.estado); end if;

  v_allowed := case v_order.estado
    when 'pedido_recibido' then p_estado in ('pago_verificado', 'cancelado')
    when 'pago_verificado' then p_estado in ('en_preparacion', 'cancelado')
    when 'en_preparacion' then p_estado in ('en_camino', 'cancelado')
    when 'en_camino' then p_estado = 'entregado'
    else false
  end;
  if not v_allowed then raise exception 'TRANSICION_INVALIDA'; end if;
  if p_estado = 'pago_verificado' and v_order.pago_declarado is null then raise exception 'PAGO_NO_DECLARADO'; end if;

  if p_estado = 'cancelado' then perform public.liberar_stock_pedido(v_order.id); end if;
  update public.pedidos set
    estado = p_estado,
    reserva_expira_en = case when p_estado <> 'pedido_recibido' then null else reserva_expira_en end,
    fecha_pago_verificado = case when p_estado = 'pago_verificado' then now() else fecha_pago_verificado end,
    fecha_preparacion = case when p_estado = 'en_preparacion' then now() else fecha_preparacion end,
    fecha_envio = case when p_estado = 'en_camino' then now() else fecha_envio end,
    fecha_entrega = case when p_estado = 'entregado' then now() else fecha_entrega end
   where id = p_pedido_id;

  insert into public.pedido_historial (pedido_id, estado_anterior, estado_nuevo, cambiado_por)
  values (v_order.id, v_order.estado, p_estado, auth.uid());
  return jsonb_build_object('id', v_order.id, 'estado', p_estado);
end;
$$;

revoke all on function public.cambiar_estado_pedido(bigint, text) from public, anon;
grant execute on function public.cambiar_estado_pedido(bigint, text) to authenticated;

create or replace function public.obtener_seguimiento_por_codigo(p_codigo text)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'codigo_seguimiento', codigo_seguimiento,
    'cliente_nombre', coalesce(cliente_nombre, 'Cliente'),
    'total', total, 'metodo_pago', metodo_pago,
    'estado', coalesce(estado, 'pedido_recibido'), 'fecha', fecha,
    'fecha_pago_verificado', fecha_pago_verificado,
    'fecha_preparacion', fecha_preparacion,
    'fecha_envio', fecha_envio, 'fecha_entrega', fecha_entrega
  )
  from public.pedidos
  where upper(codigo_seguimiento) = upper(trim(p_codigo))
    and (usuario_id = auth.uid() or public.is_admin())
    and (pago_declarado is not null or estado <> 'pedido_recibido')
  limit 1;
$$;

revoke all on function public.obtener_seguimiento_por_codigo(text) from public, anon;
grant execute on function public.obtener_seguimiento_por_codigo(text) to authenticated;

-- El catálogo recibe una fila por producto; PostgreSQL agrega las reseñas.
create or replace view public.productos_catalogo
with (security_invoker = true)
as
select
  p.id, p.nombre, p.categoria, p.precio, p.precio_original, p.imagen, p.stock,
  p.descripcion, p.caracteristicas, p.imagenes_extra, p.video_url, p.marca, p.garantia,
  round(avg(r.calificacion)::numeric, 1) as rating,
  count(r.id)::integer as review_count
from public.productos p
left join public.resenas r on r.producto_id = p.id and r.aprobada = true
group by p.id;

grant select on public.productos_catalogo to anon, authenticated;

create or replace function public.resumen_admin()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_result jsonb;
begin
  if not public.is_admin() then raise exception 'FORBIDDEN'; end if;
  select jsonb_build_object(
    'pedidos_pagados', count(*),
    'ingresos_verificados', coalesce(sum(total), 0),
    'delivery_cobrado', coalesce(sum(costo_delivery), 0)
  ) into v_result
  from public.pedidos
  where estado in ('pago_verificado', 'en_preparacion', 'en_camino', 'entregado');
  return v_result;
end;
$$;

revoke all on function public.resumen_admin() from public, anon;
grant execute on function public.resumen_admin() to authenticated;

commit;
